default_stages: [commit]
exclude: ^(config/cmake/cpm/deps-generated.cmake|config/bazel/recipes.bzl)$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.2.0'
    hooks:
      - id: check-added-large-files
        args: ['--maxkb', '5000']
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 'v2.25.0'
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.6.2'
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: 'v0.32.0'
    hooks:
      - id: yapf
        additional_dependencies: [toml]
  - repo: https://github.com/asottile/pyupgrade
    rev: 'v2.32.1'
    hooks:
      - id: pyupgrade
  - repo: https://github.com/PyCQA/isort
    rev: '5.10.1'
    hooks:
      - id: isort
        args: ['--line-length=100']
  - repo: https://github.com/golangci/golangci-lint
    rev: 'v1.46.1'
    hooks:
      - id: golangci-lint
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: 'v3.4.3-1'
    hooks:
      - id: shfmt
        args: ['-w', '-i', '2', '-s', '-l', '-ci']
