version: '3'

tasks:
  restart-batch:
    - docker compose -f stack.yaml kill {{.ARGS}} --remove-orphans
    - docker compose -f stack.yaml rm -f {{.ARGS}}
    - docker compose -f stack.yaml build {{.ARGS}}
    - docker compose -f stack.yaml up {{.ARGS}} -d --remove-orphans
  remove-all:
    - docker compose -f stack.yaml kill --remove-orphans
    - docker compose -f stack.yaml rm -f
  restart-data:
    - task: restart-batch
      vars:
        ARGS: zookeeper mysql canal adminer kafka kafka_ui_kowl hadoop hive spark flink warmup
  build-sre-image:
    - >
      docker buildx build . --network=host --file common/docker/Dockerfile.ubuntu-sre --push
      --cache-to=type=inline
      --cache-from=type=registry,ref=curoky/sidecar:ubuntu22.10-sre
      --tag curoky/sidecar:ubuntu22.10-sre
  register-host:
    - echo '172.20.0.19 kafka' >> /etc/hosts
    - echo '172.20.0.20 hadoop' >> /etc/hosts
    - echo '172.20.0.22 mysql' >> /etc/hosts
    - echo '172.20.0.25 hive' >> /etc/hosts
