name: Build images

on:
  push:
    paths:
      - '.github/workflows/build-image.yaml'
      - 'common/docker/**'
  schedule:
    - cron: '0 0 28 * *'
  workflow_dispatch:

jobs:
  build-ubuntu-sre:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: curoky
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: .
          file: common/docker/Dockerfile.ubuntu-sre
          push: true
          tags: curoky/sidecar:ubuntu22.04-sre
          cache-from: type=registry,ref=curoky/sidecar:ubuntu22.04-sre
          cache-to: type=inline
